## flask-pod.yaml
## Input File for K8S to create Docker Container 
---
apiVersion: v1
kind: Pod
metadata:
    name: flask-pod
spec:
    containers:
    -   name: flask-pod
        image: localhost:32000/simple:testlocal  
        ports:
        -   containerPort: 5000
