## flask-controller.yml
## Configuration for Replication Controller K8S
---
apiVersion: v1
kind: ReplicationController
metadata:
    name: flask-server
    namespace: default
    labels:
        name: flask-server
spec:
    replicas: 3
    selector:
        name: flask-server
    template:
        metadata:
            labels:
                name: flask-server
        spec:
            containers:
            -   name: flask-server
                image: localhost:32000/simple-docker
                imagePullPolicy: IfNotPresent
                ports:
                -   containerPort: 5000
            restartPolicy: Always

                
                
                